#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint || exit 1
npm test || exit 1
npm run build || exit 1

if [ -n "$CF_PUBLISH" ]; then
  npm run proxy:publish || exit 1
fi

if [ -n "$GAS_DEPLOYMENT_ID" ]; then
  node scripts/gas-deploy.js || exit 1
fi
